### ISSUE TITLE
ERROR   | Password is required for key ~/.ssh/id_rsa

### ISSUE THREAD

**Issue by cyriltasse** [mhardcastle/lotss-query#5]
Hi trying to access lotss database,

```
In [1]: from surveys_db import SurveysDB

In [2]: sdb=SurveysDB()
2022-02-07 15:48:00,769| ERROR   | Password is required for key /home/cyril.tasse/.ssh/id_rsa

```

my `~/.surveys` file looks like

```
<theCommonSLotssPWD>
tasse
id_rsa.survey
```

and my `.ssh/config`

```
ForwardAgent yes
ForwardX11 yes
```

The problems happens here: https://github.com/mhardcastle/lotss-query/blob/55bf5e637535c1d347300b331acadb7e6c2f7c0d/surveys_db.py#L195

Whatever option I played with

```
 sshtunnel.SSHTunnelForwarder(
    ssh_address_or_host=None,
    ssh_config_file='~/.ssh/config',
    ssh_host_key=None,
    ssh_password=None,
    ssh_pkey=None,
    ssh_private_key_password=None,
    ssh_proxy=None,
    ssh_proxy_enabled=True,
    ssh_username=None,
    local_bind_address=None,
    local_bind_addresses=None)
```

leep to the same message and `sshtunnel` keeps using `~/.ssh/id_rsa` private key

Also

```
cyril.tasse@nancep6:~$ ssh -i ~/.ssh/id_rsa.survey tasse@lofar.herts.ac.uk
Last login: Mon Feb  7 15:42:32 2022 from nancep6.obs-nancay.fr
tasse@lofar-server:~$ logout
Connection to lofar.herts.ac.uk closed.
cyril.tasse@nancep6:~$ ssh -i ~/.ssh/id_rsa tasse@lofar.herts.ac.uk
Last login: Mon Feb  7 16:02:14 2022 from nancep6.obs-nancay.fr
```

both work...

So I'm a little bit dry, any idea?

**Comment by mhardcastle** [comment]
Hi Cyril,

I think what's going on is that new versions of sshtunnel have use_agent=True by default and this pulls in other keys in your .ssh directory.

For me the code I've just pushed forces it to use one key and one key only. Try a pull and see if it solves the problem.

Cheers

Martin

**Comment by cyriltasse** [comment]
Hey thanks @mhardcastle for looking into this... 

I just pulled, checked that the code has changed and is applying the changes, but I still have the same error message:

` 2022-02-08 10:44:07,475| ERROR   | Password is required for key /home/cyril.tasse/.ssh/id_rsa`

What's super puzzling is that the exact same code used to work back in may... Could it be related to a system change/update?

**Comment by mhardcastle** [comment]
That is weird. I can force the code to use a specified key with what I pushed... What is your `sshtunnel.__version__` ?

**Comment by mhardcastle** [comment]
(and has your sshtunnel been upgraded recently perhaps?)

**Comment by cyriltasse** [comment]
I have 

```
In [8]: sshtunnel.__version__
Out[8]: '0.4.0'
```

**Comment by mhardcastle** [comment]
Ah, that gives me something to work with. That's the newest version and the one that ships with Debian is quite a bit older by the look of things. I will see if I can repeat the tests I've done here on this version.

**Comment by cyriltasse** [comment]
What's your version? I can try to downgrade perhaps...

**Comment by mhardcastle** [comment]
Would be good to fix this permanently though by making something that works with the newer version.

It seems to me as though they have actually broken the logic for key selection in newer versions... let me have a look...

**Comment by cyriltasse** [comment]
What I don't get anyway is that I don't think anything had changed in my virtualenv (and 0.4.0 was released in Jan 11 2021 - so way before I've installed) since May 21, and it was working fine at that time...

**Comment by mhardcastle** [comment]
I've made a change which should force recent versions of sshtunnel to use only the key you specify. The issue is that it's loading in your other key even if you tell it not to.

Can you pull again (one more time) and see if it works? If not, can you do sdb=SurveysDB(verbose=True) and post the output here?

**Comment by cyriltasse** [comment]
Ok Interesting, it goes a step further to `self.tunnel.start()`


```
n [5]: sdb=SurveysDB(verbose=True)
MySQL host is lofar-server.data
Cannot find host lofar-server.data will use tunnel
2022-02-08 21:53:48,658| INFO    | 0 key(s) loaded
2022-02-08 21:53:48,659| INFO    | Connecting to gateway: lofar.herts.ac.uk:22 as user 'tasse'
2022-02-08 21:53:48,659| DEBUG   | Concurrent connections allowed: True
2022-02-08 21:53:48,661| DEBUG   | Trying to log in with key: b'5ac9eb68367acdd54679ac618a656e97'
2022-02-08 21:53:48,682| DEBUG   | Transport socket info: (<AddressFamily.AF_INET: 2>, 2049, 0), timeout=0.1
2022-02-08 21:53:48,948| DEBUG   | Authentication error
2022-02-08 21:53:48,948| WARNING | Tunnels are not started. Please .start() first!
2022-02-08 21:53:48,948| INFO    | Closing ssh transport
2022-02-08 21:53:48,949| DEBUG   | Transport is closed
2022-02-08 21:53:48,949| ERROR   | Could not open connection to gateway
---------------------------------------------------------------------------
BaseSSHTunnelForwarderError               Traceback (most recent call last)
<ipython-input-5-f25a0cf291a0> in <module>
----> 1 sdb=SurveysDB(verbose=True)

/data/cyril.tasse/VE_Py3_nancep6/sources/lotss-query/surveys_db.py in __init__(self, readonly, verbose, survey)
    209                                                          # if allow_agent is true it may find other keys
    210                                                          )
--> 211                 self.tunnel.start()
    212                 localport=self.tunnel.local_bind_port
    213                 self.con = mdb.connect(host='127.0.0.1', user='survey_user', password=self.password, database=self.database, port=localport, cursorclass=mdbcursors.DictCursor)

/data/cyril.tasse/VE_Py3_nancep6/lib/python3.6/site-packages/sshtunnel.py in start(self)
   1330         if not self.is_active:
   1331             self._raise(BaseSSHTunnelForwarderError,
-> 1332                         reason='Could not establish session to SSH gateway')
   1333         for _srv in self._server_list:
   1334             thread = threading.Thread(

/data/cyril.tasse/VE_Py3_nancep6/lib/python3.6/site-packages/sshtunnel.py in _raise(self, exception, reason)
   1172     def _raise(self, exception=BaseSSHTunnelForwarderError, reason=None):
   1173         if self._raise_fwd_exc:
-> 1174             raise exception(reason)
   1175         else:
   1176             self.logger.error(repr(exception(reason)))

BaseSSHTunnelForwarderError: Could not establish session to SSH gateway
> /data/cyril.tasse/VE_Py3_nancep6/lib/python3.6/site-packages/sshtunnel.py(1174)_raise()
   1172     def _raise(self, exception=BaseSSHTunnelForwarderError, reason=None):
   1173         if self._raise_fwd_exc:
-> 1174             raise exception(reason)
   1175         else:
   1176             self.logger.error(repr(exception(reason)))

```

**Comment by mhardcastle** [comment]
Well this is very odd. I guess we have now forced it to use the right key, but it's not authenticating with it. What's more, I can't see anything in the logs to show that the connection even happened.

**Comment by cyriltasse** [comment]
Hey, I've just set `allow_agent=True` and now that works!

**Comment by mhardcastle** [comment]
Bizarre. Well I guess we can just push that version and hope it works for others. For me that allows it to try other keys than the one specified in the .surveys file which is kind of the opposite of what we want... but if it works...

**Comment by cyriltasse** [comment]
Thanks @mhardcastle that's great I can now access the database...
